LMS/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('MyLMS.urls',namespace='MyLMS')),
]

MyLMS/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .import views

urlpatterns = [
    url(r'^$', views.welcome_page,name='welcome_page'),
    url(r'^welcome/', views.welcome_page,name='welcome_page'),
    url(r'^login/$', views.login_page, name='login_page'),
    url(r'^login/1$', views.login_action, name='login_action'),
    url(r'^signup/$', views.signup_page, name='signup_page'),
    url(r'^signup/1$', views.signup_action, name='signup_action'),
    url(r'^logout/$', views.logout_action, name='logout_action'),
    url(r'^index/$', views.index, name='index'),
    url(r'^bookslist/$', views.bookslist,name='bookslist'),
    url(r'^record/$', views.record_page,name='record_page'),
    url(r'^record/delete(?P<record_id>[0-9]+)$', views.delete_waiting,name='delete_waiting'),
    url(r'^book/(?P<book_id>[0-9]+)$', views.book_page,name='book_page'),
    url(r'^record/borrow$', views.borrow_action,name='borrow_action'),
    url(r'^bookslist/search/$', views.search_action,name='search_action'),
    url(r'^settings/$', views.settings, name='settings'),

]

MyLMS/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

#书库
class Book(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Book_ID')
    Available = models.BooleanField(default=1)
    Title = models.CharField(max_length=64,default='')
    Author = models.CharField(max_length=32, default='')
    ISBN = models.CharField(max_length=32, default='')
    Publisher = models.CharField(max_length=32, default='')
    Pub_Time = models.DateField(null=True)
    Pages = models.IntegerField(null=True)
    Description = models.TextField(null=True)
    Position = models.CharField(max_length=8, default='A-101')
    Price = models.DecimalField(max_digits=4, decimal_places=2, default=35)
    #Modified_Time = models.DateTimeField(auto_now=True)
    #此方法为打印到屏幕上对象的标记为其title值
    def __unicode__(self):
        return  str(self.id)

class Reader(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Reader_ID')
    Name = models.CharField(max_length=16, null=False,unique=True)
    StudentCard = models.CharField(max_length=16, null=False,unique=True)
    Password = models.CharField(max_length=16, null=False)
    Active = models.BooleanField(default=0)
    def __unicode__(self):
        return str(self.id)

class Record(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Record_ID')
    Book = models.ForeignKey('Book',on_delete=models.CASCADE,related_name="The_Book")
    Reader = models.ForeignKey('Reader',on_delete=models.CASCADE,)
    Created_time = models.DateTimeField(auto_now_add = True)
    Modified_time = models.DateTimeField(auto_now=True)
    Fine = models.DecimalField(max_digits=4,decimal_places=2,default=0)
    WAITFORCHECK = 'WAITFORCHECK'
    BORROWED = 'BORROWED'
    RETURNED = 'RETURNED'
    TURNDOWN = 'TURNDOWN'
    DEMAGE = 'DEMAGE'
    STATUS_CHOICES = (
        ( WAITFORCHECK, 'WAITFORCHECK'),
        ( BORROWED , 'BORROWED'),
        ( RETURNED , 'RETURNED'),
        ( TURNDOWN , 'TURNDOWN'),
        ( DEMAGE , 'DEMAGE'),
    )
    Status = models.CharField(
        max_length=16,
        choices=STATUS_CHOICES,
        default=WAITFORCHECK,
    )

    def __unicode__(self):
        return str(self.id)

class FineStatistic(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Fine_ID')
    Begin_time = models.DateField(blank=True, null=True)
    End_time = models.DateField(blank=True, null=True)
    Reader =  models.ForeignKey('Reader',on_delete=models.CASCADE,blank=True,null=True)
    TotalFine = models.DecimalField(max_digits=8,decimal_places=2,default=0,null = True)

    def __unicode__(self):
        return str(self.id)


class AddbyISBN(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AddRecord_ID')
    ISBN = models.CharField(max_length=32, default='')
    Number = models.IntegerField(default=1)
    Price = models.DecimalField(max_digits=4, decimal_places=2, default=35.00)
    Position = models.CharField(max_length=8, default='A-101')

    def __unicode__(self):
        return str(self.id)

MyLMS/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from . import models
from django.db.models import Q,Count,Sum


#欢迎界面
def welcome_page(request):
    return render(request,'welcome.html')

#登陆界面
def login_page(request):
    return render(request,'login.html',{'line': 'Please input your readername and your password!'})

#登陆操作处理
def login_action(request):
    namefield = request.POST.get('namefield', None)
    pwdfield = request.POST.get('pwdfield', None)
    if namefield:
        if pwdfield:
            reader = models.Reader.objects.filter(Name=namefield, Password=pwdfield).first()
            if reader :
                request.session['reader_id'] = reader.id
                request.session.set_expiry(600)
                request.session['reader_name'] = reader.Name
                books = models.Book.objects.all()
                if reader.Active :
                    return render(request, 'index.html',)
                else:
                    return render(request, 'login.html',{'line': 'Please Active your account First!'})
    return render(request, 'login.html', {'line': 'Login failure!Please checkout your readername and your password!'})

#注册界面
def signup_page(request):
    return render(request,'signup.html',{'line': 'Please input your readername and your password!'})


#注册操作处理
def signup_action(request):
    namefield = request.POST.get('namefield', None)
    pwdfield = request.POST.get('pwdfield', None)
    scfield = request.POST.get('scfield', None)
    if namefield :
        r = models.Reader.objects.filter(Name=namefield).first()
        if r:
            return render(request, 'signup.html',
                          {'line': 'Signup failure!Readername has been used!'})
        if scfield:
            r = models.Reader.objects.filter(Name=namefield).first()
            if r:
                return render(request, 'signup.html',
                              {'line': 'Signup failure!StudentCard has been used!'})
        if pwdfield:
            r = models.Reader(Name=namefield, Password = pwdfield,StudentCard = scfield)
            r.save()
            return render(request, 'login.html', {'line': 'Signup Success!'})
    return render(request, 'signup.html', {'line': 'Signup failure!Please checkout your readername and your password!'})

#用户登出
def logout_action(request):
    try:
        del request.session['reader_id']
    except KeyError:
        pass
    return render(request, 'login.html', {'line': 'You have logged out!'})

#用户首页
def index(request):
    if "reader_id" not in request.session:
        return render(request, 'login.html', {'line': 'Please login first!'})
    #最活跃的3个用户
    readers = models.Record.objects.values_list('Reader').annotate(Borrow_num=Count('id')).order_by('-Borrow_num')
    reader = models.Reader.objects.get(pk=readers[0][0])
    Top1={'id':readers[0][0],'name':reader.Name,'Act_times':readers[0][1]}
    reader = models.Reader.objects.get(pk=readers[1][0])
    Top2 = {'id': readers[1][0], 'name': reader.Name, 'Act_times': readers[1][1]}
    reader = models.Reader.objects.get(pk=readers[2][0])
    Top3 = {'id': readers[2][0], 'name': reader.Name, 'Act_times': readers[2][1]}
    #最新增加的7本书记
    Newbooks = models.Book.objects.all().order_by('-id')[0:7]
    #可用/总数目
    sum = models.Book.objects.all().count()
    available = models.Book.objects.filter(Available=True).count()
    per = (float (available) / float (sum) )*100
    booksum = {'sum':sum,'available':available,'per':int(per)}
    #借书记录
    records = models.Record.objects.filter(Reader=request.session["reader_id"]).values_list('Status').annotate(Count('id'))
    BORROWED = 0
    WAITFORCHECK = 0
    TURNDOWN = 0
    DEMAGE = 0
    RETURNED = 0
    for item in records:
        if item[0] == 'BORROWED':
            BORROWED=item[1]
        if item[0] == 'WAITFORCHECK':
            WAITFORCHECK=item[1]
        if item[0] == 'TURNDOWN':
            TURNDOWN=item[1]
        if item[0] == 'DEMAGE':
            DEMAGE=item[1]
        if item[0] == 'RETURNED':
            RETURNED=item[1]
    #罚款总数
    record = models.Record.objects.filter(Reader=request.session["reader_id"])
    t = record.aggregate(Sum('Fine'))['Fine__sum']
    if t:
        TotalFine = t
    else:
        TotalFine = 0
    return render(request,'index.html',{'Top1':Top1,'Top2':Top2,'Top3':Top3,'Newbooks':Newbooks,'booksum':booksum,'TotalFine':TotalFine,'BORROWED':BORROWED,'WAITFORCHECK':WAITFORCHECK,'TURNDOWN':TURNDOWN,'DEMAGE':DEMAGE,'RETURNED':RETURNED})

#图书馆书单
def bookslist(request):
    if "reader_id" in request.session:
        books = models.Book.objects.all()
        booksall = books.count()
        limit = 13  # 每页显示的记录数
        paginator = Paginator(books, limit)  # 实例化一个分页对象
        page = request.GET.get('page')  # 获取页码
        try:
            books = paginator.page(page)  # 获取某页对应的记录
        except PageNotAnInteger:  # 如果页码不是个整数
            books = paginator.page(1)  # 取第一页的记录
        except EmptyPage:  # 如果页码太大，没有相应的记录
            books = paginator.page(paginator.num_pages)  # 取最后一页的记录
        reader = models.Reader.objects.get(pk=request.session["reader_id"])
        return render(request, 'bookslist.html', {'books': books,'booksall': booksall, 'reader' : reader})
    else:
        return render(request, 'login.html', {'line': 'Please login first!'})

# 借书记录
def record_page(request):
    if "reader_id" not in request.session:
        return render(request, 'login.html', {'line': 'Please login first!'})
    records = models.Record.objects.filter(Reader=request.session["reader_id"]).order_by('-Created_time')
    recordsall = records.count()
    limit = 13  # 每页显示的记录数
    paginator = Paginator(records, limit)  # 实例化一个分页对象
    page = request.GET.get('page')  # 获取页码
    try:
        records = paginator.page(page)  # 获取某页对应的记录
    except PageNotAnInteger:  # 如果页码不是个整数
        records = paginator.page(1)  # 取第一页的记录
    except EmptyPage:  # 如果页码太大，没有相应的记录
        records = paginator.page(paginator.num_pages)  # 取最后一页的记录
    return render(request, 'record_page.html', {'records': records,'recordsall': recordsall,'line':"(●'◡'●) Your Borrow Record As Follow :" })

#用户删除申请借书记录
def delete_waiting(request,record_id):
    models.Record.objects.filter(pk=record_id).delete()
    records = models.Record.objects.filter(Reader=request.session["reader_id"])
    recordsall = records.count()
    return render(request, 'record_page.html', {'records': records,'recordsall': recordsall,'line':"(●'◡'●) Delete the borrow request sucessfully:" })


#书籍详情页
def book_page(request,book_id):
    if "reader_id" not in request.session:
        return render(request, 'login.html', {'line': 'Please login first!'})
    book = models.Book.objects.get(pk=book_id)
    return render(request,'book_page.html',{'book':book})

#用户发出借书申请
def borrow_action(request):
    if "reader_id" not in request.session:
        return render(request, 'login.html', {'line': 'Please login first!'})
    Bookid = request.POST.get('book_id', None)
    book = models.Book.objects.get(pk=Bookid)
    # 最多同时借两本书
    records = models.Record.objects.filter(Reader=request.session["reader_id"]).filter(Q(Status='BORROWED')|Q(Status='WAITFORCHECK'))
    if records.count() > 1:
        return render(request, 'book_page.html',
                      {'book': book, 'line': "You have already borrowed or tried to borrow Two book!"})
    # 不能借同一本书
    BookISBN = request.POST.get('book_ISBN', None)
    for record in records:
        if BookISBN == record.Book.ISBN:
            return render(request, 'book_page.html', {'book': book,'line':"You have borrowed or tried to borrow this book!"})

    #正常申请并跳转
    book = models.Book.objects.get(pk=Bookid)
    reader = models.Reader.objects.get(pk=request.session["reader_id"])
    if book :
        r = models.Record(Book=book, Reader=reader)
        r.save()
    records = models.Record.objects.filter(Reader=request.session["reader_id"])
    return render(request, 'record_page.html', {'records': records , 'line':"(●'◡'●) Now you can bring the book and find Libarian to check out:"})



#搜索并返回结果
def search_action(request):
    if "reader_id" in request.session:
        title = request.POST.get('title', None)
        if title:
            books = models.Book.objects.filter(Title=title)
        else:
            books = models.Book.objects.all()
        booksall = books.count()
        limit = 13  # 每页显示的记录数
        paginator = Paginator(books, limit)  # 实例化一个分页对象
        page = request.GET.get('page')  # 获取页码
        try:
            books = paginator.page(page)  # 获取某页对应的记录
        except PageNotAnInteger:  # 如果页码不是个整数
            books = paginator.page(1)  # 取第一页的记录
        except EmptyPage:  # 如果页码太大，没有相应的记录
            books = paginator.page(paginator.num_pages)  # 取最后一页的记录
        reader = models.Reader.objects.get(pk=request.session["reader_id"])
        return render(request, 'bookslist.html', {'books': books,'booksall': booksall, 'reader' : reader})
    else:
        return render(request, 'login.html', {'line': 'Please login first!'})


def settings(request):
    if "reader_id" not in request.session:
        return render(request, 'login.html', {'line': 'Please login first!'})
    reader = models.Reader.objects.get(pk=request.session["reader_id"])
    return render(request,'settings.html',{'reader':reader})
    pass

MyLMS/templates/bookslist.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Bookslist - LibraryMS</title>
        <link rel="shortcut icon" href="/static/assets/img/favicon.png" type="image/x-icon" />
		<link rel="stylesheet" href="/static/assets/css/amazeui.css" />
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="/static/assets/css/core.css" />
		<link rel="stylesheet" href="/static/assets/css/menu.css" />
		<link rel="stylesheet" href="/static/assets/css/index.css" />
		<link rel="stylesheet" href="/static/assets/css/admin.css" />
		<link rel="stylesheet" href="/static/assets/css/page/typography.css" />
		<link rel="stylesheet" href="/static/assets/css/page/form.css" />
	</head>
	<body>
		<!-- Begin page -->
		<header class="am-topbar am-topbar-fixed-top">
			<div class="am-topbar-left am-hide-sm-only">
                <a href="{% url 'MyLMS:index' %}" class="logo">Library<span>MS</span></span><i class="zmdi zmdi-layers"></i></a>
            </div>

			<div class="contain">
				<ul class="am-nav am-navbar-nav am-navbar-left">
					<li><h4 class="page-title">Hi! {{request.session.reader_name}}.o(^▽^)o Welcome to Library!  </h4></li>
				</ul>
				<ul class="am-nav am-navbar-nav am-navbar-right">
					<li class="inform"><i class="am-icon-bell-o" aria-hidden="true"></i></li>
					<li class="hidden-xs am-hide-sm-only">
                        <form role="search" class="app-search" action="{% url 'MyLMS:search_action' %}" method="POST">
                            {% csrf_token %}
                            <input type="text" name = "title" value="" placeholder="Search..." class="form-control">
                            <img src="/static/assets/img/search.png">
                            <input type="submit" value="">
                        </form>
                    </li>
				</ul>
			</div>
		</header>
		<!-- end page -->


		<div class="admin">
		    <!-- ========== Left Sidebar Start ========== -->
            <!-- sidebar start -->
            <div class="admin-sidebar am-offcanvas  am-padding-0" id="admin-offcanvas">
            <div class="am-offcanvas-bar admin-offcanvas-bar">
                <!-- User -->
                <div class="user-box am-hide-sm-only">
                    <div class="user-img">
                        <img src="/static/assets/img/avatar-1.jpg" alt="user-img" title="user_img" class="img-circle img-thumbnail img-responsive">
                    </div>
                    <h5>{{request.session.reader_name}}</h5>
                    <ul class="list-inline">
                        <li>
                            <a href="{% url 'MyLMS:settings' %}">
                                <button class="am-btn am-btn-default am-btn-xs am-text-secondary"><span class="fa fa-cog"> </span> Settings</button>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'MyLMS:logout_action' %}">
                                <button class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span class="am-icon-dot-circle-o"> </span> Logout </button>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- End User -->

                 <ul class="am-list admin-sidebar-list">
                    <li><a href="{% url 'MyLMS:index' %}"><span class="am-icon-home"></span>  Home </a></li>
                    <li><a href="{% url 'MyLMS:bookslist' %}"><span class="am-icon-copy"></span>  Books List </a></li>

                    <li><a href="{% url 'MyLMS:record_page' %}"><span class="am-icon-table"></span>  Borrow Record </a></li>
                    <li><a href="{% url 'MyLMS:settings' %}"><span class="fa fa-cog"></span>  Settings </a></li>
                    <li><a href=""><span class="am-icon-line-chart"></span>  Data Chart </a></li>
                      <li>.  </li>
                  </ul>
            </div>
            </div>
            <!-- sidebar end -->
            <!-- ========== Left Sidebar end ========== -->

		    <!-- ============================================================== -->
		    <!-- Start right Content here -->
		    <div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="card-box">
					<!-- Row start -->
					<div class="am-g">
                        <div class="am-u-sm-12">
                            <form class="am-form">
                                <table class="am-table am-table-striped am-table-hover table-main">
                                    <thead>
                                    <tr>
                                        <th class="table-id">ID</th>
                                        <th class="table-title">Title</th>
                                        <th class="table-type">Author</th>
                                        <th class="table-author am-hide-sm-only">ISBN</th>
                                        <th class="table-set">Publisher</th>
                                        <th class="table-date am-hide-sm-only">Pub_Time</th>
                                        <th class="table-title">Position</th>

                                    </tr>
                                    </thead>

                                    <tbody>
                                      {% for book in books.object_list  %}
                                      <tr>
                                        <td>{{ book.id }}</td>
                                        <td><a href="{% url 'MyLMS:book_page' book.id %}">{{ book.Title }}</a></td>
                                        <td>{{ book.Author}}</td>
                                        <td class="am-hide-sm-only">{{book.ISBN}}</td>
                                        <td class="am-hide-sm-only">{{book.Publisher}}</td>
                                        <td class="am-hide-sm-only">{{book.Pub_Time}}</td>
                                        <td>{{book.Position}}</td>
                                        {% if book.Available   %}
                                          <td><span class="label label-success"><i class="am-icon-thumbs-o-up"></i></span></td>
                                        {% else %}
                                           <td><span class="label label-danger"><i class="am-icon-close"></i></span></td>
                                        {% endif %}
                                      </tr>
                                      {% endfor %}
                                      </tbody>
                                </table>
                                <div class="am-cf">
                                  Currently displayed {{ books | length }} books / A total of {{ booksall }} books here
                                  <div class="am-fr">
                                    <ul class="am-pagination">
                                        {% if books.has_previous %}
                                          <li><a href="?page={{ books.previous_page_number }}">«</a></li>
                                        {% endif %}
                                        <!--{# books.paginator.number_pages 返回总页数 #}-->
                                          Page {{ books.number }} of {{ books.paginator.num_pages }}.
                                        {% if books.has_next %}
                                          <li><a href="?page={{ books.next_page_number }}">»</a></li>
                                        {% endif %}
                                      <!--{# books.paginator.page_range 这个函数返回包含一个所有页码数的 range 对象 #}-->
                                      <!--{# 即 range(1, books.paginator.num_pages + 1) #}-->
                                      {% for page_number in books.paginator.page_range %}
                                      {% ifequal page_number  books.number %}
                                        <li class="am-active"><a href="#">{{ page_number }}</a></li>
                                      {% else %}
                                        <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                                      {% endifequal %}
                                      {% endfor %}
                                    </ul>
                                  </div>
                                </div>
                                <hr />
                                <p>Tips：Some tips should be written here (●'◡'●)</p>
                            </form>
                        </div>

                     </div>
                    <!-- Row end -->

                </div>
            </div>
        </div>
            <!-- end right Content here -->
        </div>


		<!-- navbar -->
		<a href="admin-offcanvas" class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu" data-am-offcanvas="{target: '#admin-offcanvas'}"></a>

		<script type="text/javascript" src="/static/assets/js/jquery-2.1.0.js" ></script>
		<script type="text/javascript" src="/static/assets/js/amazeui.min.js"></script>
		<script type="text/javascript" src="/static/assets/js/app.js" ></script>
		<script type="text/javascript" src="/static/assets/js/blockUI.js" ></script>
	</body>

</html>

MyLMS/templates/settings.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Settings - LibraryMS</title>
        <link rel="shortcut icon" href="/static/assets/img/favicon.png" type="image/x-icon" />
		<link rel="stylesheet" href="/static/assets/css/amazeui.css" />
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="/static/assets/css/core.css" />
		<link rel="stylesheet" href="/static/assets/css/menu.css" />
		<link rel="stylesheet" href="/static/assets/css/index.css" />
		<link rel="stylesheet" href="/static/assets/css/admin.css" />
		<link rel="stylesheet" href="/static/assets/css/page/typography.css" />
		<link rel="stylesheet" href="/static/assets/css/page/form.css" />
	</head>
	<body>
		<!-- Begin page -->
		<header class="am-topbar am-topbar-fixed-top">
			<div class="am-topbar-left am-hide-sm-only">
                <a href="{% url 'MyLMS:index' %}" class="logo">Library<span>MS</span></span><i class="zmdi zmdi-layers"></i></a>
            </div>

			<div class="contain">
				<ul class="am-nav am-navbar-nav am-navbar-left">
					<li><h4 class="page-title">(●'◡'●) Your info As Follow：  </h4></li>
				</ul>
				<ul class="am-nav am-navbar-nav am-navbar-right">
					<li class="inform"><i class="am-icon-bell-o" aria-hidden="true"></i></li>
				</ul>
			</div>
		</header>
		<!-- end page -->


		<div class="admin">
		    <!-- ========== Left Sidebar Start ========== -->
            <!-- sidebar start -->
            <div class="admin-sidebar am-offcanvas  am-padding-0" id="admin-offcanvas">
            <div class="am-offcanvas-bar admin-offcanvas-bar">
                <!-- User -->
                <div class="user-box am-hide-sm-only">
                    <div class="user-img">
                        <img src="/static/assets/img/avatar-1.jpg" alt="user-img" title="user_img" class="img-circle img-thumbnail img-responsive">
                    </div>
                    <h5>{{request.session.reader_name}}</h5>
                    <ul class="list-inline">
                        <li>
                            <a href="{% url 'MyLMS:settings' %}">

                                <button class="am-btn am-btn-default am-btn-xs am-text-secondary"><span class="fa fa-cog"> </span> Settings</button>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'MyLMS:logout_action' %}">
                                <button class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span class="am-icon-dot-circle-o"> </span> Logout </button>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- End User -->

                 <ul class="am-list admin-sidebar-list">
                    <li><a href="{% url 'MyLMS:index' %}"><span class="am-icon-home"></span>  Home </a></li>
                     <li><a href="{% url 'MyLMS:bookslist' %}"><span class="am-icon-copy"></span>  Books List </a></li>
                    <li><a href="{% url 'MyLMS:record_page' %}"><span class="am-icon-table"></span>  Borrow Record </a></li>
                    <li><a href="{% url 'MyLMS:settings' %}"><span class="fa fa-cog"></span>  Settings </a></li>
                     <li><a href=""><span class="am-icon-line-chart"></span>  Data Chart </a></li>
                     <li>.  </li>
                  </ul>
            </div>
          </div>
            <!-- sidebar end -->
            <!-- ========== Left Sidebar end ========== -->

		    <!-- ============================================================== -->
		    <!-- Start right Content here -->
		    <div class="content-page">
                <!-- row start -->
			<div class="am-g">
				<!-- col start -->
				<div class="am-u-md-11">
					<div class="card-box">
						<div class="am-form-success">
							    <label><font size = "6">Your Readername  : {{ reader.Name }}</font></label>
                        </div>

						<div class="am-btn-xs am-text-secondary">

							    <label><font size = "4">Your ID : {{ reader.id }}</font></label>
                                <br>
                                <label><font size = "4">Your StudentCard: {{ reader.StudentCard }}</font></label>
                                <br>
                        </div>


                        <hr />
                        <p>Tips：Sorry!You are not allow to  Change Your INFO by yourself (●'◡'●)Find Library</p>
					</div>
				</div>

				<!-- col end -->

            </div>
            </div>
            <!-- end right Content here -->
        </div>


		<!-- navbar -->
		<a href="admin-offcanvas" class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu" data-am-offcanvas="{target: '#admin-offcanvas'}"></a>

		<script type="text/javascript" src="/static/assets/js/jquery-2.1.0.js" ></script>
		<script type="text/javascript" src="/static/assets/js/amazeui.min.js"></script>
		<script type="text/javascript" src="/static/assets/js/app.js" ></script>
		<script type="text/javascript" src="/static/assets/js/blockUI.js" ></script>
	</body>

</html>

MyLMS/templates/welcome.html
<!DOCTYPE html>
<!-- saved from url=(0027)http://m-union.net.cn/login -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <title>Welcome - LibraryMS</title>
  <link rel="shortcut icon" href="/static/assets/img/favicon.png" type="image/x-icon" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'welcome_files\login.css' %}" >
  <style>
  body{height:100%;background:#16a085;overflow:hidden;}
  canvas{z-index:-1;position:absolute;}
  </style>
</head>
<body>


  <dl class="admin_login">
    <dt >
        <strong>Welcome to Library Management System</strong>
        <br>
        <strong>Who are U?</strong>
    </dt>

    <dd align="center">
        <a href="{% url 'MyLMS:login_page' %}" class="submit_btn" >I'm a Reader!</a>
    </dd>
    <dd align="center">
        <a href="http://localhost:8000/admin/MyLMS/" class="submit_btn" >I'm an Administrator!</a>
    </dd>
  </dl>

  <script src="{% static 'welcome_files\jquery-2.1.1.js.下载' %}"></script>
  <script src="{% static 'welcome_files\Particleground.js.下载' %}"></script>
  <script>
  $(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
  dotColor: '#5cbdaa',
  lineColor: '#5cbdaa'
  });
  });
  </script>

</body></html>